Matplotlib created a temporary config/cache directory at /tmp/matplotlib-zrtvpfui because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-dz2ju2_5 because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-a5i4fh17 because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-j_v4tj6b because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-j7fhqvog because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-7sclicq9 because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-o_rcmra0 because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-tg274e6e because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-8o9ldh2s because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-bzqlmaai because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-tmg433k0 because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-s319_jww because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-0bd48sij because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-b09oylxo because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-ppddm8v6 because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-k3g8lh2k because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-_rl1s9qg because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-y3fffkuf because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-9kfw23so because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-0ol9psd5 because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-fxf_bxee because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-zb0bb58v because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-a3x6ab_m because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-funfpykc because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-qzlnam2y because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-g4g0ecmj because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-e6322gsy because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-irdi9gcv because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-wzo3jte9 because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-aha9rxqb because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-zfgfht8h because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-q5bpl0hw because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-854xaxi0 because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-vxhbz2ks because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-qoccu2n8 because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-ybz77so8 because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-vvq66mk9 because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-u10zfpni because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-qm80bmvg because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-npuctjwz because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-p0d0fa_d because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-2wj1_xup because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-io05wenm because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-j5fwkaib because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-rqkpgisn because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-eyzfwt1f because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-9p7w9osd because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-8fnd7j72 because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
:::MLLOG {"namespace": "", "time_ms": 1617330220706, "event_type": "POINT_IN_TIME", "key": "submission_benchmark", "value": "deepcam", "metadata": {"file": "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/utils/mlperf_log_utils.py", "lineno": 56}}
:::MLLOG {"namespace": "", "time_ms": 1617330220873, "event_type": "POINT_IN_TIME", "key": "submission_org", "value": "Umbrella Corp.", "metadata": {"file": "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/utils/mlperf_log_utils.py", "lineno": 59}}
:::MLLOG {"namespace": "", "time_ms": 1617330220873, "event_type": "POINT_IN_TIME", "key": "submission_division", "value": "closed", "metadata": {"file": "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/utils/mlperf_log_utils.py", "lineno": 62}}
:::MLLOG {"namespace": "", "time_ms": 1617330220873, "event_type": "POINT_IN_TIME", "key": "submission_status", "value": "onprem", "metadata": {"file": "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/utils/mlperf_log_utils.py", "lineno": 65}}
:::MLLOG {"namespace": "", "time_ms": 1617330220873, "event_type": "POINT_IN_TIME", "key": "submission_platform", "value": "48xSUBMISSION_PLATFORM_PLACEHOLDER", "metadata": {"file": "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/utils/mlperf_log_utils.py", "lineno": 68}}
:::MLLOG {"namespace": "", "time_ms": 1617330220874, "event_type": "INTERVAL_START", "key": "init_start", "value": null, "metadata": {"file": "src/deepCam/train_hdf5_ddp.py", "lineno": 109}}
:::MLLOG {"namespace": "", "time_ms": 1617330220874, "event_type": "POINT_IN_TIME", "key": "cache_clear", "value": null, "metadata": {"file": "src/deepCam/train_hdf5_ddp.py", "lineno": 110}}
:::MLLOG {"namespace": "", "time_ms": 1617330220874, "event_type": "POINT_IN_TIME", "key": "seed", "value": 333, "metadata": {"file": "src/deepCam/train_hdf5_ddp.py", "lineno": 114}}
:::MLLOG {"namespace": "", "time_ms": 1617330220878, "event_type": "POINT_IN_TIME", "key": "global_batch_size", "value": 384, "metadata": {"file": "src/deepCam/train_hdf5_ddp.py", "lineno": 187}}
:::MLLOG {"namespace": "", "time_ms": 1617330220878, "event_type": "POINT_IN_TIME", "key": "opt_name", "value": "LAMB", "metadata": {"file": "src/deepCam/train_hdf5_ddp.py", "lineno": 188}}
:::MLLOG {"namespace": "", "time_ms": 1617330220879, "event_type": "POINT_IN_TIME", "key": "opt_base_learning_rate", "value": 0.001, "metadata": {"file": "src/deepCam/train_hdf5_ddp.py", "lineno": 189}}
:::MLLOG {"namespace": "", "time_ms": 1617330220879, "event_type": "POINT_IN_TIME", "key": "opt_learning_rate_warmup_steps", "value": 0, "metadata": {"file": "src/deepCam/train_hdf5_ddp.py", "lineno": 190}}
:::MLLOG {"namespace": "", "time_ms": 1617330220879, "event_type": "POINT_IN_TIME", "key": "opt_learning_rate_warmup_factor", "value": 1.0, "metadata": {"file": "src/deepCam/train_hdf5_ddp.py", "lineno": 191}}
:::MLLOG {"namespace": "", "time_ms": 1617330220879, "event_type": "POINT_IN_TIME", "key": "opt_epsilon", "value": 1e-08, "metadata": {"file": "src/deepCam/train_hdf5_ddp.py", "lineno": 192}}
Constructing DeepLabv3+ model...
Number of output channels: 3
Output stride: 16
Number of Input Channels: 16
Selected optimization level O1:  Insert automatic casts around Pytorch functions and Tensor methods.

Defaults for this optimization level are:
enabled                : True
opt_level              : O1
cast_model_type        : None
patch_torch_functions  : True
keep_batchnorm_fp32    : None
master_weights         : None
loss_scale             : dynamic
Processing user overrides (additional kwargs that are not None)...
After processing overrides, optimization options are:
enabled                : True
opt_level              : O1
cast_model_type        : None
patch_torch_functions  : True
keep_batchnorm_fp32    : None
master_weights         : None
loss_scale             : dynamic
Initialized dataset with  5760  samples.
Initialized dataset with  576  samples.
:::MLLOG {"namespace": "", "time_ms": 1617330226176, "event_type": "POINT_IN_TIME", "key": "train_samples", "value": 5760, "metadata": {"file": "src/deepCam/train_hdf5_ddp.py", "lineno": 309}}
:::MLLOG {"namespace": "", "time_ms": 1617330226176, "event_type": "POINT_IN_TIME", "key": "eval_samples", "value": 576, "metadata": {"file": "src/deepCam/train_hdf5_ddp.py", "lineno": 314}}
:::MLLOG {"namespace": "", "time_ms": 1617330237942, "event_type": "INTERVAL_END", "key": "init_stop", "value": null, "metadata": {"file": "src/deepCam/train_hdf5_ddp.py", "lineno": 335}}
:::MLLOG {"namespace": "", "time_ms": 1617330237943, "event_type": "INTERVAL_START", "key": "run_start", "value": null, "metadata": {"file": "src/deepCam/train_hdf5_ddp.py", "lineno": 336}}
:::MLLOG {"namespace": "", "time_ms": 1617330237944, "event_type": "INTERVAL_START", "key": "epoch_start", "value": null, "metadata": {"file": "src/deepCam/train_hdf5_ddp.py", "lineno": 342, "epoch_num": 1, "step_num": 0}}
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 442, in forward
    x, low_level_features = self.xception_features(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 225, in forward
    x = self.block18(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 112, in forward
    x = self.rep(inp)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 65, in forward
    x = self.pointwise(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 419, in forward
    return self._conv_forward(input, self.weight)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 416, in _conv_forward
    self.padding, self.dilation, self.groups)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: CUDA out of memory. Tried to allocate 40.00 MiB (GPU 0; 15.75 GiB total capacity; 14.12 GiB already allocated; 86.88 MiB free; 14.31 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 442, in forward
    x, low_level_features = self.xception_features(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 225, in forward
    x = self.block18(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 112, in forward
    x = self.rep(inp)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 65, in forward
    x = self.pointwise(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 419, in forward
    return self._conv_forward(input, self.weight)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 416, in _conv_forward
    self.padding, self.dilation, self.groups)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: CUDA out of memory. Tried to allocate 40.00 MiB (GPU 0; 15.75 GiB total capacity; 14.12 GiB already allocated; 86.94 MiB free; 14.31 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 442, in forward
    x, low_level_features = self.xception_features(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 225, in forward
    x = self.block18(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 112, in forward
    x = self.rep(inp)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 65, in forward
    x = self.pointwise(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 419, in forward
    return self._conv_forward(input, self.weight)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 416, in _conv_forward
    self.padding, self.dilation, self.groups)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: CUDA out of memory. Tried to allocate 40.00 MiB (GPU 0; 15.75 GiB total capacity; 14.12 GiB already allocated; 86.88 MiB free; 14.31 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 442, in forward
    x, low_level_features = self.xception_features(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 225, in forward
    x = self.block18(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 112, in forward
    x = self.rep(inp)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 63, in forward
    x = fixed_padding(x, self.conv1.kernel_size[0], rate=self.conv1.dilation[0])
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 50, in fixed_padding
    padded_inputs = F.pad(inputs, (pad_beg, pad_end, pad_beg, pad_end))
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/functional.py", line 3552, in _pad
    return _VF.constant_pad_nd(input, pad, value)
RuntimeError: CUDA out of memory. Tried to allocate 42.00 MiB (GPU 0; 15.75 GiB total capacity; 14.20 GiB already allocated; 46.94 MiB free; 14.39 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 442, in forward
    x, low_level_features = self.xception_features(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 225, in forward
    x = self.block18(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 112, in forward
    x = self.rep(inp)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 63, in forward
    x = fixed_padding(x, self.conv1.kernel_size[0], rate=self.conv1.dilation[0])
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 50, in fixed_padding
    padded_inputs = F.pad(inputs, (pad_beg, pad_end, pad_beg, pad_end))
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/functional.py", line 3552, in _pad
    return _VF.constant_pad_nd(input, pad, value)
RuntimeError: CUDA out of memory. Tried to allocate 42.00 MiB (GPU 0; 15.75 GiB total capacity; 14.20 GiB already allocated; 46.94 MiB free; 14.39 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 442, in forward
    x, low_level_features = self.xception_features(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 225, in forward
    x = self.block18(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 112, in forward
    x = self.rep(inp)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 65, in forward
    x = self.pointwise(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 419, in forward
    return self._conv_forward(input, self.weight)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 416, in _conv_forward
    self.padding, self.dilation, self.groups)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: CUDA out of memory. Tried to allocate 40.00 MiB (GPU 0; 15.75 GiB total capacity; 14.12 GiB already allocated; 86.94 MiB free; 14.31 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 442, in forward
    x, low_level_features = self.xception_features(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 225, in forward
    x = self.block18(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 112, in forward
    x = self.rep(inp)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 136, in forward
    self.weight, self.bias, bn_training, exponential_average_factor, self.eps)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/functional.py", line 2016, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: CUDA out of memory. Tried to allocate 40.00 MiB (GPU 0; 15.75 GiB total capacity; 14.16 GiB already allocated; 70.94 MiB free; 14.35 GiB reserved in total by PyTorch)
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 442, in forward
    x, low_level_features = self.xception_features(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 225, in forward
    x = self.block18(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 112, in forward
    x = self.rep(inp)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 65, in forward
    x = self.pointwise(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 419, in forward
    return self._conv_forward(input, self.weight)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 416, in _conv_forward
    self.padding, self.dilation, self.groups)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: CUDA out of memory. Tried to allocate 40.00 MiB (GPU 0; 15.75 GiB total capacity; 14.12 GiB already allocated; 86.88 MiB free; 14.31 GiB reserved in total by PyTorch)
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 442, in forward
    x, low_level_features = self.xception_features(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 225, in forward
    x = self.block18(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 112, in forward
    x = self.rep(inp)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 63, in forward
    x = fixed_padding(x, self.conv1.kernel_size[0], rate=self.conv1.dilation[0])
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 50, in fixed_padding
    padded_inputs = F.pad(inputs, (pad_beg, pad_end, pad_beg, pad_end))
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/functional.py", line 3552, in _pad
    return _VF.constant_pad_nd(input, pad, value)
RuntimeError: CUDA out of memory. Tried to allocate 42.00 MiB (GPU 0; 15.75 GiB total capacity; 14.20 GiB already allocated; 46.94 MiB free; 14.39 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 442, in forward
    x, low_level_features = self.xception_features(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 225, in forward
    x = self.block18(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 112, in forward
    x = self.rep(inp)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 63, in forward
    x = fixed_padding(x, self.conv1.kernel_size[0], rate=self.conv1.dilation[0])
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 50, in fixed_padding
    padded_inputs = F.pad(inputs, (pad_beg, pad_end, pad_beg, pad_end))
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/functional.py", line 3552, in _pad
    return _VF.constant_pad_nd(input, pad, value)
RuntimeError: CUDA out of memory. Tried to allocate 42.00 MiB (GPU 0; 15.75 GiB total capacity; 14.20 GiB already allocated; 46.94 MiB free; 14.39 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 442, in forward
    x, low_level_features = self.xception_features(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 225, in forward
    x = self.block18(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 112, in forward
    x = self.rep(inp)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 63, in forward
    x = fixed_padding(x, self.conv1.kernel_size[0], rate=self.conv1.dilation[0])
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 50, in fixed_padding
    padded_inputs = F.pad(inputs, (pad_beg, pad_end, pad_beg, pad_end))
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/functional.py", line 3552, in _pad
    return _VF.constant_pad_nd(input, pad, value)
RuntimeError: CUDA out of memory. Tried to allocate 42.00 MiB (GPU 0; 15.75 GiB total capacity; 14.20 GiB already allocated; 46.94 MiB free; 14.39 GiB reserved in total by PyTorch)
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 442, in forward
    x, low_level_features = self.xception_features(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 225, in forward
    x = self.block18(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 112, in forward
    x = self.rep(inp)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 65, in forward
    x = self.pointwise(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 419, in forward
    return self._conv_forward(input, self.weight)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 416, in _conv_forward
    self.padding, self.dilation, self.groups)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: CUDA out of memory. Tried to allocate 40.00 MiB (GPU 0; 15.75 GiB total capacity; 14.12 GiB already allocated; 86.94 MiB free; 14.31 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 442, in forward
    x, low_level_features = self.xception_features(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 225, in forward
    x = self.block18(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 112, in forward
    x = self.rep(inp)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 63, in forward
    x = fixed_padding(x, self.conv1.kernel_size[0], rate=self.conv1.dilation[0])
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 50, in fixed_padding
    padded_inputs = F.pad(inputs, (pad_beg, pad_end, pad_beg, pad_end))
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/functional.py", line 3552, in _pad
    return _VF.constant_pad_nd(input, pad, value)
RuntimeError: CUDA out of memory. Tried to allocate 42.00 MiB (GPU 0; 15.75 GiB total capacity; 14.20 GiB already allocated; 46.94 MiB free; 14.39 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 442, in forward
    x, low_level_features = self.xception_features(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 225, in forward
    x = self.block18(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 112, in forward
    x = self.rep(inp)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 63, in forward
    x = fixed_padding(x, self.conv1.kernel_size[0], rate=self.conv1.dilation[0])
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 50, in fixed_padding
    padded_inputs = F.pad(inputs, (pad_beg, pad_end, pad_beg, pad_end))
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/functional.py", line 3552, in _pad
    return _VF.constant_pad_nd(input, pad, value)
RuntimeError: CUDA out of memory. Tried to allocate 42.00 MiB (GPU 0; 15.75 GiB total capacity; 14.20 GiB already allocated; 46.94 MiB free; 14.39 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 442, in forward
    x, low_level_features = self.xception_features(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 225, in forward
    x = self.block18(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 112, in forward
    x = self.rep(inp)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 65, in forward
    x = self.pointwise(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 419, in forward
    return self._conv_forward(input, self.weight)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 416, in _conv_forward
    self.padding, self.dilation, self.groups)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: CUDA out of memory. Tried to allocate 40.00 MiB (GPU 0; 15.75 GiB total capacity; 14.12 GiB already allocated; 86.94 MiB free; 14.31 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 442, in forward
    x, low_level_features = self.xception_features(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 225, in forward
    x = self.block18(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 112, in forward
    x = self.rep(inp)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 65, in forward
    x = self.pointwise(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 419, in forward
    return self._conv_forward(input, self.weight)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 416, in _conv_forward
    self.padding, self.dilation, self.groups)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: CUDA out of memory. Tried to allocate 40.00 MiB (GPU 0; 15.75 GiB total capacity; 14.12 GiB already allocated; 86.94 MiB free; 14.31 GiB reserved in total by PyTorch)
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 442, in forward
    x, low_level_features = self.xception_features(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 225, in forward
    x = self.block18(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 112, in forward
    x = self.rep(inp)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 136, in forward
    self.weight, self.bias, bn_training, exponential_average_factor, self.eps)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/functional.py", line 2016, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: CUDA out of memory. Tried to allocate 40.00 MiB (GPU 0; 15.75 GiB total capacity; 14.16 GiB already allocated; 70.94 MiB free; 14.35 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 442, in forward
    x, low_level_features = self.xception_features(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 225, in forward
    x = self.block18(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 112, in forward
    x = self.rep(inp)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 63, in forward
    x = fixed_padding(x, self.conv1.kernel_size[0], rate=self.conv1.dilation[0])
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 50, in fixed_padding
    padded_inputs = F.pad(inputs, (pad_beg, pad_end, pad_beg, pad_end))
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/functional.py", line 3552, in _pad
    return _VF.constant_pad_nd(input, pad, value)
RuntimeError: CUDA out of memory. Tried to allocate 42.00 MiB (GPU 0; 15.75 GiB total capacity; 14.20 GiB already allocated; 46.94 MiB free; 14.39 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 442, in forward
    x, low_level_features = self.xception_features(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 225, in forward
    x = self.block18(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 112, in forward
    x = self.rep(inp)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 63, in forward
    x = fixed_padding(x, self.conv1.kernel_size[0], rate=self.conv1.dilation[0])
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 50, in fixed_padding
    padded_inputs = F.pad(inputs, (pad_beg, pad_end, pad_beg, pad_end))
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/functional.py", line 3552, in _pad
    return _VF.constant_pad_nd(input, pad, value)
RuntimeError: CUDA out of memory. Tried to allocate 42.00 MiB (GPU 0; 15.75 GiB total capacity; 14.20 GiB already allocated; 46.94 MiB free; 14.39 GiB reserved in total by PyTorch)
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 442, in forward
    x, low_level_features = self.xception_features(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 225, in forward
    x = self.block18(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 112, in forward
    x = self.rep(inp)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 136, in forward
    self.weight, self.bias, bn_training, exponential_average_factor, self.eps)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/functional.py", line 2016, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: CUDA out of memory. Tried to allocate 40.00 MiB (GPU 0; 15.75 GiB total capacity; 14.16 GiB already allocated; 70.94 MiB free; 14.35 GiB reserved in total by PyTorch)
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 442, in forward
    x, low_level_features = self.xception_features(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 225, in forward
    x = self.block18(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 112, in forward
    x = self.rep(inp)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 136, in forward
    self.weight, self.bias, bn_training, exponential_average_factor, self.eps)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/functional.py", line 2016, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: CUDA out of memory. Tried to allocate 40.00 MiB (GPU 0; 15.75 GiB total capacity; 14.16 GiB already allocated; 70.94 MiB free; 14.35 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 442, in forward
    x, low_level_features = self.xception_features(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 225, in forward
    x = self.block18(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 112, in forward
    x = self.rep(inp)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 63, in forward
    x = fixed_padding(x, self.conv1.kernel_size[0], rate=self.conv1.dilation[0])
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 50, in fixed_padding
    padded_inputs = F.pad(inputs, (pad_beg, pad_end, pad_beg, pad_end))
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/functional.py", line 3552, in _pad
    return _VF.constant_pad_nd(input, pad, value)
RuntimeError: CUDA out of memory. Tried to allocate 42.00 MiB (GPU 0; 15.75 GiB total capacity; 14.20 GiB already allocated; 46.94 MiB free; 14.39 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 442, in forward
    x, low_level_features = self.xception_features(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 225, in forward
    x = self.block18(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 112, in forward
    x = self.rep(inp)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 63, in forward
    x = fixed_padding(x, self.conv1.kernel_size[0], rate=self.conv1.dilation[0])
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 50, in fixed_padding
    padded_inputs = F.pad(inputs, (pad_beg, pad_end, pad_beg, pad_end))
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/functional.py", line 3552, in _pad
    return _VF.constant_pad_nd(input, pad, value)
RuntimeError: CUDA out of memory. Tried to allocate 42.00 MiB (GPU 0; 15.75 GiB total capacity; 14.20 GiB already allocated; 46.94 MiB free; 14.39 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 442, in forward
    x, low_level_features = self.xception_features(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 225, in forward
    x = self.block18(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 112, in forward
    x = self.rep(inp)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 63, in forward
    x = fixed_padding(x, self.conv1.kernel_size[0], rate=self.conv1.dilation[0])
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 50, in fixed_padding
    padded_inputs = F.pad(inputs, (pad_beg, pad_end, pad_beg, pad_end))
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/functional.py", line 3552, in _pad
    return _VF.constant_pad_nd(input, pad, value)
RuntimeError: CUDA out of memory. Tried to allocate 42.00 MiB (GPU 0; 15.75 GiB total capacity; 14.20 GiB already allocated; 46.94 MiB free; 14.39 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 442, in forward
    x, low_level_features = self.xception_features(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 225, in forward
    x = self.block18(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 112, in forward
    x = self.rep(inp)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 65, in forward
    x = self.pointwise(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 419, in forward
    return self._conv_forward(input, self.weight)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 416, in _conv_forward
    self.padding, self.dilation, self.groups)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: CUDA out of memory. Tried to allocate 40.00 MiB (GPU 0; 15.75 GiB total capacity; 14.12 GiB already allocated; 86.94 MiB free; 14.31 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 442, in forward
    x, low_level_features = self.xception_features(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 225, in forward
    x = self.block18(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 112, in forward
    x = self.rep(inp)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 65, in forward
    x = self.pointwise(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 419, in forward
    return self._conv_forward(input, self.weight)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 416, in _conv_forward
    self.padding, self.dilation, self.groups)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: CUDA out of memory. Tried to allocate 40.00 MiB (GPU 0; 15.75 GiB total capacity; 14.12 GiB already allocated; 86.94 MiB free; 14.31 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 442, in forward
    x, low_level_features = self.xception_features(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 225, in forward
    x = self.block18(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 112, in forward
    x = self.rep(inp)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 63, in forward
    x = fixed_padding(x, self.conv1.kernel_size[0], rate=self.conv1.dilation[0])
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 50, in fixed_padding
    padded_inputs = F.pad(inputs, (pad_beg, pad_end, pad_beg, pad_end))
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/functional.py", line 3552, in _pad
    return _VF.constant_pad_nd(input, pad, value)
RuntimeError: CUDA out of memory. Tried to allocate 42.00 MiB (GPU 0; 15.75 GiB total capacity; 14.20 GiB already allocated; 46.94 MiB free; 14.39 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 442, in forward
    x, low_level_features = self.xception_features(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 225, in forward
    x = self.block18(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 112, in forward
    x = self.rep(inp)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 63, in forward
    x = fixed_padding(x, self.conv1.kernel_size[0], rate=self.conv1.dilation[0])
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 50, in fixed_padding
    padded_inputs = F.pad(inputs, (pad_beg, pad_end, pad_beg, pad_end))
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/functional.py", line 3552, in _pad
    return _VF.constant_pad_nd(input, pad, value)
RuntimeError: CUDA out of memory. Tried to allocate 42.00 MiB (GPU 0; 15.75 GiB total capacity; 14.20 GiB already allocated; 46.94 MiB free; 14.39 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 442, in forward
    x, low_level_features = self.xception_features(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 225, in forward
    x = self.block18(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 112, in forward
    x = self.rep(inp)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 65, in forward
    x = self.pointwise(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 419, in forward
    return self._conv_forward(input, self.weight)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 416, in _conv_forward
    self.padding, self.dilation, self.groups)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: CUDA out of memory. Tried to allocate 40.00 MiB (GPU 0; 15.75 GiB total capacity; 14.12 GiB already allocated; 86.94 MiB free; 14.31 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 442, in forward
    x, low_level_features = self.xception_features(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 225, in forward
    x = self.block18(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 112, in forward
    x = self.rep(inp)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 136, in forward
    self.weight, self.bias, bn_training, exponential_average_factor, self.eps)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/functional.py", line 2016, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: CUDA out of memory. Tried to allocate 40.00 MiB (GPU 0; 15.75 GiB total capacity; 14.16 GiB already allocated; 70.94 MiB free; 14.35 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 442, in forward
    x, low_level_features = self.xception_features(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 225, in forward
    x = self.block18(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 112, in forward
    x = self.rep(inp)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 63, in forward
    x = fixed_padding(x, self.conv1.kernel_size[0], rate=self.conv1.dilation[0])
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 50, in fixed_padding
    padded_inputs = F.pad(inputs, (pad_beg, pad_end, pad_beg, pad_end))
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/functional.py", line 3552, in _pad
    return _VF.constant_pad_nd(input, pad, value)
RuntimeError: CUDA out of memory. Tried to allocate 42.00 MiB (GPU 0; 15.75 GiB total capacity; 14.20 GiB already allocated; 46.94 MiB free; 14.39 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 442, in forward
    x, low_level_features = self.xception_features(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 225, in forward
    x = self.block18(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 112, in forward
    x = self.rep(inp)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 63, in forward
    x = fixed_padding(x, self.conv1.kernel_size[0], rate=self.conv1.dilation[0])
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 50, in fixed_padding
    padded_inputs = F.pad(inputs, (pad_beg, pad_end, pad_beg, pad_end))
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/functional.py", line 3552, in _pad
    return _VF.constant_pad_nd(input, pad, value)
RuntimeError: CUDA out of memory. Tried to allocate 42.00 MiB (GPU 0; 15.75 GiB total capacity; 14.20 GiB already allocated; 46.94 MiB free; 14.39 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 442, in forward
    x, low_level_features = self.xception_features(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 225, in forward
    x = self.block18(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 112, in forward
    x = self.rep(inp)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 63, in forward
    x = fixed_padding(x, self.conv1.kernel_size[0], rate=self.conv1.dilation[0])
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 50, in fixed_padding
    padded_inputs = F.pad(inputs, (pad_beg, pad_end, pad_beg, pad_end))
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/functional.py", line 3552, in _pad
    return _VF.constant_pad_nd(input, pad, value)
RuntimeError: CUDA out of memory. Tried to allocate 42.00 MiB (GPU 0; 15.75 GiB total capacity; 14.20 GiB already allocated; 46.94 MiB free; 14.39 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 442, in forward
    x, low_level_features = self.xception_features(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 225, in forward
    x = self.block18(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 112, in forward
    x = self.rep(inp)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 136, in forward
    self.weight, self.bias, bn_training, exponential_average_factor, self.eps)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/functional.py", line 2016, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: CUDA out of memory. Tried to allocate 40.00 MiB (GPU 0; 15.75 GiB total capacity; 14.16 GiB already allocated; 70.94 MiB free; 14.35 GiB reserved in total by PyTorch)
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 442, in forward
    x, low_level_features = self.xception_features(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 225, in forward
    x = self.block18(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 112, in forward
    x = self.rep(inp)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 65, in forward
    x = self.pointwise(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 419, in forward
    return self._conv_forward(input, self.weight)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 416, in _conv_forward
    self.padding, self.dilation, self.groups)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: CUDA out of memory. Tried to allocate 40.00 MiB (GPU 0; 15.75 GiB total capacity; 14.12 GiB already allocated; 86.88 MiB free; 14.31 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 442, in forward
    x, low_level_features = self.xception_features(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 225, in forward
    x = self.block18(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 112, in forward
    x = self.rep(inp)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 65, in forward
    x = self.pointwise(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 419, in forward
    return self._conv_forward(input, self.weight)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 416, in _conv_forward
    self.padding, self.dilation, self.groups)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: CUDA out of memory. Tried to allocate 40.00 MiB (GPU 0; 15.75 GiB total capacity; 14.12 GiB already allocated; 86.88 MiB free; 14.31 GiB reserved in total by PyTorch)
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 442, in forward
    x, low_level_features = self.xception_features(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 225, in forward
    x = self.block18(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 112, in forward
    x = self.rep(inp)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 63, in forward
    x = fixed_padding(x, self.conv1.kernel_size[0], rate=self.conv1.dilation[0])
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 50, in fixed_padding
    padded_inputs = F.pad(inputs, (pad_beg, pad_end, pad_beg, pad_end))
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/functional.py", line 3552, in _pad
    return _VF.constant_pad_nd(input, pad, value)
RuntimeError: CUDA out of memory. Tried to allocate 42.00 MiB (GPU 0; 15.75 GiB total capacity; 14.20 GiB already allocated; 46.88 MiB free; 14.39 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 442, in forward
    x, low_level_features = self.xception_features(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 225, in forward
    x = self.block18(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 112, in forward
    x = self.rep(inp)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 65, in forward
    x = self.pointwise(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 419, in forward
    return self._conv_forward(input, self.weight)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 416, in _conv_forward
    self.padding, self.dilation, self.groups)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: CUDA out of memory. Tried to allocate 40.00 MiB (GPU 0; 15.75 GiB total capacity; 14.12 GiB already allocated; 86.88 MiB free; 14.31 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 442, in forward
    x, low_level_features = self.xception_features(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 225, in forward
    x = self.block18(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 112, in forward
    x = self.rep(inp)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 65, in forward
    x = self.pointwise(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 419, in forward
    return self._conv_forward(input, self.weight)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 416, in _conv_forward
    self.padding, self.dilation, self.groups)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: CUDA out of memory. Tried to allocate 40.00 MiB (GPU 0; 15.75 GiB total capacity; 14.12 GiB already allocated; 86.94 MiB free; 14.31 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 442, in forward
    x, low_level_features = self.xception_features(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 225, in forward
    x = self.block18(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 112, in forward
    x = self.rep(inp)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 65, in forward
    x = self.pointwise(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 419, in forward
    return self._conv_forward(input, self.weight)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 416, in _conv_forward
    self.padding, self.dilation, self.groups)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: CUDA out of memory. Tried to allocate 40.00 MiB (GPU 0; 15.75 GiB total capacity; 14.12 GiB already allocated; 86.94 MiB free; 14.31 GiB reserved in total by PyTorch)
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 442, in forward
    x, low_level_features = self.xception_features(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 225, in forward
    x = self.block18(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 112, in forward
    x = self.rep(inp)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 136, in forward
    self.weight, self.bias, bn_training, exponential_average_factor, self.eps)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/functional.py", line 2016, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: CUDA out of memory. Tried to allocate 40.00 MiB (GPU 0; 15.75 GiB total capacity; 14.16 GiB already allocated; 70.94 MiB free; 14.35 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 442, in forward
    x, low_level_features = self.xception_features(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 225, in forward
    x = self.block18(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 112, in forward
    x = self.rep(inp)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 63, in forward
    x = fixed_padding(x, self.conv1.kernel_size[0], rate=self.conv1.dilation[0])
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 50, in fixed_padding
    padded_inputs = F.pad(inputs, (pad_beg, pad_end, pad_beg, pad_end))
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/functional.py", line 3552, in _pad
    return _VF.constant_pad_nd(input, pad, value)
RuntimeError: CUDA out of memory. Tried to allocate 42.00 MiB (GPU 0; 15.75 GiB total capacity; 14.20 GiB already allocated; 46.94 MiB free; 14.39 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 442, in forward
    x, low_level_features = self.xception_features(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 225, in forward
    x = self.block18(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 112, in forward
    x = self.rep(inp)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 63, in forward
    x = fixed_padding(x, self.conv1.kernel_size[0], rate=self.conv1.dilation[0])
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 50, in fixed_padding
    padded_inputs = F.pad(inputs, (pad_beg, pad_end, pad_beg, pad_end))
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/functional.py", line 3552, in _pad
    return _VF.constant_pad_nd(input, pad, value)
RuntimeError: CUDA out of memory. Tried to allocate 42.00 MiB (GPU 0; 15.75 GiB total capacity; 14.20 GiB already allocated; 46.94 MiB free; 14.39 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 442, in forward
    x, low_level_features = self.xception_features(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 225, in forward
    x = self.block18(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 112, in forward
    x = self.rep(inp)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 63, in forward
    x = fixed_padding(x, self.conv1.kernel_size[0], rate=self.conv1.dilation[0])
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 50, in fixed_padding
    padded_inputs = F.pad(inputs, (pad_beg, pad_end, pad_beg, pad_end))
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/functional.py", line 3552, in _pad
    return _VF.constant_pad_nd(input, pad, value)
RuntimeError: CUDA out of memory. Tried to allocate 42.00 MiB (GPU 0; 15.75 GiB total capacity; 14.20 GiB already allocated; 46.94 MiB free; 14.39 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 442, in forward
    x, low_level_features = self.xception_features(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 225, in forward
    x = self.block18(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 112, in forward
    x = self.rep(inp)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 136, in forward
    self.weight, self.bias, bn_training, exponential_average_factor, self.eps)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/functional.py", line 2016, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: CUDA out of memory. Tried to allocate 40.00 MiB (GPU 0; 15.75 GiB total capacity; 14.16 GiB already allocated; 86.75 MiB free; 14.35 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 442, in forward
    x, low_level_features = self.xception_features(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 225, in forward
    x = self.block18(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 112, in forward
    x = self.rep(inp)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 136, in forward
    self.weight, self.bias, bn_training, exponential_average_factor, self.eps)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/functional.py", line 2016, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: CUDA out of memory. Tried to allocate 40.00 MiB (GPU 0; 15.75 GiB total capacity; 14.16 GiB already allocated; 70.94 MiB free; 14.35 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 442, in forward
    x, low_level_features = self.xception_features(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 225, in forward
    x = self.block18(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 112, in forward
    x = self.rep(inp)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 63, in forward
    x = fixed_padding(x, self.conv1.kernel_size[0], rate=self.conv1.dilation[0])
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 50, in fixed_padding
    padded_inputs = F.pad(inputs, (pad_beg, pad_end, pad_beg, pad_end))
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/functional.py", line 3552, in _pad
    return _VF.constant_pad_nd(input, pad, value)
RuntimeError: CUDA out of memory. Tried to allocate 42.00 MiB (GPU 0; 15.75 GiB total capacity; 14.20 GiB already allocated; 46.94 MiB free; 14.39 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 442, in forward
    x, low_level_features = self.xception_features(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 225, in forward
    x = self.block18(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 112, in forward
    x = self.rep(inp)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 63, in forward
    x = fixed_padding(x, self.conv1.kernel_size[0], rate=self.conv1.dilation[0])
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 50, in fixed_padding
    padded_inputs = F.pad(inputs, (pad_beg, pad_end, pad_beg, pad_end))
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/functional.py", line 3552, in _pad
    return _VF.constant_pad_nd(input, pad, value)
RuntimeError: CUDA out of memory. Tried to allocate 42.00 MiB (GPU 0; 15.75 GiB total capacity; 14.20 GiB already allocated; 46.94 MiB free; 14.39 GiB reserved in total by PyTorch)
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
